---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    dnf:
      update_cache: yes
  
  - name: install apache2 pacakge
    dnf:
      name: httpd
      state: latest

  - name: add php support for apache
    dnf:
      name: 
        - php
        - php-cli
        - php-common
        - php-gd
        - php-json
        - php-intl
        - php-mbstring
        - php-mysqli
        - php-openssl
        - php-pdo
        - php-xml
        - php-zip 
