- name: install apache and php
  package:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start httpd(RedHat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

